#!/usr/bin/env bash
#
# Vendor-format validation, on the cluster, against PRIVATE images.
#
# RULING R3: no vendor fixture may be committed. Everything the generator can
# synthesise is tested in CI (tests/integration/formats/); .czi/.nd2/.lif/.svs/
# .qptiff can only be validated where real files exist, which is here -- and the
# EVIDENCE is committed instead of the data, as docs/validation/format_validation.md.
#
# Usage:
#   bash tests/cluster/validate_formats.sh \
#       --samplesheet /path/to/your/filled-in/samplesheet.csv \
#       --outdir      /scratch/you/format-validation \
#       --site-config conf/ieo.config
#
# The samplesheet is tests/cluster/samplesheet.template.csv with your own paths
# and channel lists. Rows for formats you do not have: delete them.
set -euo pipefail

SAMPLESHEET=""
OUTDIR=""
SITE_CONFIG=""
CONTAINER="docker://bolt3x/mirage-convert:1.0.0"

while [ $# -gt 0 ]; do
    case "$1" in
        --samplesheet) SAMPLESHEET="$2"; shift 2 ;;
        --outdir)      OUTDIR="$2";      shift 2 ;;
        --site-config) SITE_CONFIG="$2"; shift 2 ;;
        --container)   CONTAINER="$2";   shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

for required in SAMPLESHEET OUTDIR SITE_CONFIG; do
    if [ -z "${!required}" ]; then
        echo "missing --${required,,}" | tr '_' '-' >&2
        exit 2
    fi
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT="$OUTDIR/format_validation.md"
mkdir -p "$OUTDIR"
cd "$REPO_ROOT"

echo "==> Converting every slide in $SAMPLESHEET"
# --start/--stop preprocessing is the minimal path that exercises CONVERT_IMAGE
# and nothing else. --pixel_size auto is deliberate: it makes each vendor file
# assert its OWN scale, which is one of the things being validated. -with-trace
# is Nextflow's own, so wall time and peak RSS are recorded without depending on
# params.enable_trace.
nextflow run . \
    -profile singularity \
    -c "$SITE_CONFIG" \
    -with-trace "$OUTDIR/trace.txt" \
    --input "$SAMPLESHEET" \
    --outdir "$OUTDIR/run" \
    --start preprocessing \
    --stop preprocessing \
    --pixel_size auto \
    2>&1 | tee "$OUTDIR/nextflow.log"

echo "==> Probing every converted slide inside $CONTAINER"
{
    echo "# Format validation"
    echo
    echo "Generated by \`tests/cluster/validate_formats.sh\` (RULING R3: the vendor"
    echo "images are private and are never committed; this report is the evidence)."
    echo
    echo "- pipeline commit: \`$(git rev-parse HEAD)\`"
    echo "- pipeline describe: \`$(git describe --tags --always --dirty)\`"
    echo "- date (UTC): $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "- host: \`$(hostname)\`"
    echo "- nextflow: \`$(nextflow -version 2>&1 | tr '\n' ' ' | sed 's/  */ /g')\`"
    echo "- probe container: \`$CONTAINER\`"
    echo
    echo "## Inputs, as the pipeline read them"
    echo
    echo "| format | file | reader | shape (C x Y x X) | dtype | channels | pixel size (um) | probe (s) | result |"
    echo "|---|---|---|---|---|---|---|---|---|"
} > "$REPORT"

# The INPUTS: one row per samplesheet path, probed through ome_io in the image.
tail -n +2 "$SAMPLESHEET" | while IFS=, read -r _pid path _ref _channels; do
    path="${path%\"}"
    path="${path#\"}"
    [ -n "$path" ] || continue
    singularity exec --bind "$(dirname "$path")" --bind "$REPO_ROOT" "$CONTAINER" \
        python3 "$REPO_ROOT/tests/cluster/probe_image.py" --image "$path" \
        >> "$REPORT"
done

{
    echo
    echo "## Outputs, as CONVERT_IMAGE wrote them"
    echo
    echo "| format | file | reader | shape (C x Y x X) | dtype | channels | pixel size (um) | probe (s) | result |"
    echo "|---|---|---|---|---|---|---|---|---|"
} >> "$REPORT"

find "$OUTDIR/run" -name '*.ome.tif' -print0 | sort -z | while IFS= read -r -d '' out; do
    singularity exec --bind "$OUTDIR" --bind "$REPO_ROOT" "$CONTAINER" \
        python3 "$REPO_ROOT/tests/cluster/probe_image.py" \
        --image "$out" --label "converted" \
        >> "$REPORT"
done

{
    echo
    echo "## Cost, from Nextflow's own trace"
    echo
    echo '```'
    awk -F'\t' 'NR==1 || $0 ~ /CONVERT_IMAGE/ {print}' "$OUTDIR/trace.txt" \
        | cut -f 4,9,10,11 || true
    echo '```'
    echo
    echo "## Container digests recorded by the run"
    echo
    echo '```'
    # `container:` is written into every versions.yml by ProcessEnvelope.versions
    # (phase 04), so the images that produced these numbers are named in the run
    # itself rather than inferred from a tag.
    grep -rh 'container:' "$OUTDIR/run" 2>/dev/null | sort -u || echo "(none found)"
    echo '```'
} >> "$REPORT"

echo
echo "==> Report written to $REPORT"
echo "    Copy it to docs/validation/format_validation.md and commit it."
grep -c 'FAILED' "$REPORT" > /dev/null && {
    echo "    NOTE: the report contains FAILED rows -- read them before committing." >&2
}
